name: earth-analytics-python
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - numpy
  
  # Plotting
  - matplotlib
  - seaborn
  - hvplot

  # Spatial packages
  - earthpy
  - folium
  - xarray
  - rioxarray
  - rasterstats